### ISSUE TITLE
Problem converting field of java.util.List<java.lang.String>

### ISSUE THREAD

**Issue by markmelling** [uwcpdx/bean-dip#2]
Hi,

I'm converting a fairly complex java object to a clojure map, everything appears to be working correctly apart from a field that is defined as a:

`java.util.List<java.lang.String>`

When executing ClassName->map with this field defined I'm getting the error:

`CompilerException java.lang.IllegalArgumentException: No implementation of method: :bean->map of protocol: #'bean-dip.core/TranslatableToMap found for class: java.lang.String`

What do I need to do to resolve this?

Thanks

**Comment by markmelling** [comment]
It turns out that I was using an old version - `[uwcpdx/bean-dip "0.5.0"]` as mentioned in the README, rather than the latest version (0.7.2)

So the original problem is no longer an issue, although it would be good to update the README

**Comment by spieden** [comment]
I just released 0.7.3 and fully updated the README. Thanks!
