### ISSUE TITLE
bean->map doesn't work correctly when the bean has more than 8 fields

### ISSUE THREAD

**Issue by markmelling** [uwcpdx/bean-dip#3]
If a java bean has more than eight fields and these are specified in `def-translation` then not all of these fields will be converted.

I believe this is as a consequence of the way that transient maps are being used/work.

Specifically, the return value of assoc! should always be used, rather than using the original "transient" symbol returned from (clojure.core/transient {})

**Comment by spieden** [comment]
Thanks for the bug report!
